### ISSUE TITLE
Li将passwall改源了，麻烦可以将trojan-go帮加进去吗，谢谢

### ISSUE THREAD

**Issue by lllrrr2** [peter-tank/openwrt-package#1]

**Comment by lllrrr2** [comment]
开源，我打成改了。

**Comment by peter-tank** [comment]
https://github.com/peter-tank/openwrt-package/commit/924bd3f6718511bf94ec16b89ccabbbae440869a#diff-f56f6aa8d625a46cb2896718946561b0
有加啊
如果你不是指同步一下上游passwall

**Comment by lllrrr2** [comment]
不好意思，我没表达清楚，我的意思你PR，同步到上少游passwall去。

**Comment by peter-tank** [comment]
如果用trojan-go建议还是v0.6以下并暂时手动启用。我实际使用中v0.7.x 的udp tproxy还是有出错后必需重启的毛病（可能跟我固件有关吧）。而且必须要改监听端口号跟tcp统一，感觉大概率不会被接受。

**Comment by lllrrr2** [comment]
好的，谢谢，我先试用一下你的源码

**Comment by peter-tank** [comment]
提交了一个 pull request ，你可以自己试试
https://github.com/Lienol/openwrt-package/commits/226d5fdeccaa5b74a6473cea3432a1f8a08986fc
